# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 14:37
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image10',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
        migrations.AddField(
            model_name='article',
            name='image9',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.upload_location),
        ),
    ]
