# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161109_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video1',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video2',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='video3',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
