# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161115_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video1',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video2',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='video3',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
