# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161115_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True),
        ),
    ]
