# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170517_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
