# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-17 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20170517_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='age_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
