# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_f_report_nameofdocument1'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_report',
            name='nameOfDocument2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='f_report',
            name='nameOfDocument3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
