# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-14 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20170110_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f_report',
            name='author',
        ),
    ]
